repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: local
    hooks:
      - id: vitest
        name: vitest
        entry: npx vitest run
        language: system
        pass_filenames: false
        stages: [pre-commit]
